"use strict";
exports.__esModule = true;
exports["default"] = new Map([
    ['غير متزامن', 'async'],
    ['أكسر', 'break'],
    ['حالة', 'case'],
    ['أمسك', 'catch'],
    ['فئة', 'class'],
    ['ثابت', 'const'],
    ['كمل', 'continue'],
    ['مصلح', 'debugger'],
    ['معيار', 'default'],
    ['احذف', 'delete'],
    ['افعل', 'do'],
    ['وإلا', 'else'],
    ['عدد', 'enum'],
    ['اصدر', 'export'],
    ['يمتد', 'extends'],
    ['زائف', 'false'],
    ['اخيرا', 'finally'],
    ['لكل', 'for'],
    ['دالة', 'function'],
    ['اذا', 'if'],
    ['استورد', 'import'],
    ['في', 'in'],
    ['مثل', 'instanceof'],
    ['دع', 'let'],
    ['اصنع', 'new'],
    ['باطل', 'null'],
    ['رجع', 'return'],
    ['والد', 'super'],
    ['قارن', 'switch'],
    ['هذا', 'this'],
    ['ارمي', 'throw'],
    ['صادق', 'true'],
    ['حاول', 'try'],
    ['نوع', 'typeof'],
    ['متغير', 'var'],
    ['فراغ', 'void'],
    ['بينما', 'while'],
    ['مع', 'with'],
    ['تمهل', 'yield'],
    ['لوحة', 'console'],
    ['سجل', 'log'],
]);
